"""
Pydantic models mirroring TARGET_SCHEMA.json exactly.
Derived scoring fields (agent_quality_score, conversation_quality_score, hover_summary)
are computed by Node 5 of the LangGraph pipeline and stored alongside the schema fields.

SCHEMA EXTENSIONS (beyond TARGET_SCHEMA.json)
These fields are computed additions not present in the original spec.
They are intentional design choices — not schema drift.

- agent_quality_score (float):         Deterministic 0–10 composite. Computed in Node 5.
- conversation_quality_score (float):  Deterministic 0–10 composite. Computed in Node 5.
- hover_summary (str):                 2-sentence card text. Generated by Node 2 (gpt-4o-mini).
- raw_llm_output (str):                Pre-Pydantic LLM string. Stored for auditability/debugging.

All four are added to InteractionRecord as optional fields with defaults,
so the model remains fully backward-compatible with TARGET_SCHEMA.json.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional
from typing_extensions import TypedDict

from pydantic import BaseModel, Field


# ── Enums ─────────────────────────────────────────────────────────────────────

class InteractionType(str, Enum):
    SALES_INQUIRY = "sales_inquiry"
    SUPPORT_REQUEST = "support_request"
    CANCELLATION = "cancellation"
    UPGRADE_INQUIRY = "upgrade_inquiry"
    GENERAL_INQUIRY = "general_inquiry"
    COMPLAINT = "complaint"
    WIN_BACK = "win_back"


class Channel(str, Enum):
    PHONE = "phone"
    LIVE_CHAT = "live_chat"
    EMAIL = "email"


class ResolutionStatus(str, Enum):
    RESOLVED = "resolved"
    PARTIALLY_RESOLVED = "partially_resolved"
    UNRESOLVED = "unresolved"
    ESCALATED = "escalated"
    CANCELLED = "cancelled"


class CurrentPlan(str, Enum):
    FREE_TRIAL = "free_trial"
    BASIC = "basic"
    PREMIUM = "premium"
    FAMILY = "family"
    ENTERPRISE = "enterprise"
    UNKNOWN = "unknown"


class LifecycleStage(str, Enum):
    NEW = "new"
    ONBOARDING = "onboarding"
    ACTIVE = "active"
    AT_RISK = "at_risk"
    CHURNING = "churning"
    CHURNED = "churned"
    WIN_BACK = "win_back"


class AgeRange(str, Enum):
    AGE_18_25 = "18-25"
    AGE_26_35 = "26-35"
    AGE_36_45 = "36-45"
    AGE_46_55 = "46-55"
    AGE_55_PLUS = "55+"
    UNKNOWN = "unknown"


class FitnessLevel(str, Enum):
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"
    UNKNOWN = "unknown"


class SentimentOverall(str, Enum):
    VERY_NEGATIVE = "very_negative"
    NEGATIVE = "negative"
    MIXED = "mixed"
    NEUTRAL = "neutral"
    POSITIVE = "positive"
    VERY_POSITIVE = "very_positive"


class SentimentTrajectory(str, Enum):
    IMPROVING = "improving"
    STABLE = "stable"
    DECLINING = "declining"


class EmotionalIntensity(str, Enum):
    LOW = "low"
    MODERATE = "moderate"
    HIGH = "high"


class SentimentShift(str, Enum):
    POSITIVE_SPIKE = "positive_spike"
    NEGATIVE_SPIKE = "negative_spike"
    TURNING_POINT = "turning_point"


class PainSeverity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MotivationStrength(str, Enum):
    WEAK = "weak"
    MODERATE = "moderate"
    STRONG = "strong"


class CompetitorContext(str, Enum):
    CURRENTLY_USING = "currently_using"
    CONSIDERING = "considering"
    SWITCHED_TO = "switched_to"
    SWITCHED_FROM = "switched_from"
    COMPARING = "comparing"


class CompetitorSentiment(str, Enum):
    COMPETITOR_PREFERRED = "competitor_preferred"
    NEUTRAL = "neutral"
    WE_PREFERRED = "we_preferred"


class FeatureUrgency(str, Enum):
    NICE_TO_HAVE = "nice_to_have"
    IMPORTANT = "important"
    DEALBREAKER = "dealbreaker"


class ChurnRiskLevel(str, Enum):
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    IMMEDIATE = "immediate"


class UpsellLevel(str, Enum):
    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class TopicRelevance(str, Enum):
    PRIMARY = "primary"
    SECONDARY = "secondary"
    MENTIONED = "mentioned"


class TopicSentiment(str, Enum):
    POSITIVE = "positive"
    NEGATIVE = "negative"
    NEUTRAL = "neutral"


class ActionOwner(str, Enum):
    AGENT = "agent"
    CUSTOMER = "customer"
    ENGINEERING = "engineering"
    BILLING = "billing"
    PRODUCT = "product"
    MANAGEMENT = "management"


class ActionPriority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class ActionStatus(str, Enum):
    COMPLETED = "completed"
    PENDING = "pending"
    REQUIRES_FOLLOW_UP = "requires_follow_up"


class InteractionQuality(str, Enum):
    CLEAN = "clean"
    MINOR_ISSUES = "minor_issues"
    SIGNIFICANT_GAPS = "significant_gaps"


class ExtractionConfidence(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


# ── Sub-models ────────────────────────────────────────────────────────────────

class Agent(BaseModel):
    name: str
    handled_well: bool
    notable_actions: Optional[str] = None


class Resolution(BaseModel):
    status: ResolutionStatus
    summary: str


class InteractionMeta(BaseModel):
    type: InteractionType
    channel: Channel
    duration_seconds: Optional[int] = None
    agent: Agent
    resolution: Resolution


class DemographicSignals(BaseModel):
    age_range: AgeRange = AgeRange.UNKNOWN
    household: Optional[str] = None
    fitness_level: FitnessLevel = FitnessLevel.UNKNOWN


class Customer(BaseModel):
    name: Optional[str] = None
    tenure_months: Optional[int] = None
    current_plan: CurrentPlan = CurrentPlan.UNKNOWN
    lifecycle_stage: LifecycleStage
    demographic_signals: DemographicSignals = Field(default_factory=DemographicSignals)


class KeyMoment(BaseModel):
    timestamp: Optional[str] = None
    description: str
    sentiment_shift: SentimentShift
    trigger: str


class Sentiment(BaseModel):
    overall: SentimentOverall
    trajectory: SentimentTrajectory
    emotional_intensity: EmotionalIntensity
    key_moments: list[KeyMoment] = []


class PainPoint(BaseModel):
    category: str
    description: str
    severity: PainSeverity
    verbatim_quote: str
    actionable: bool


class Motivation(BaseModel):
    type: str
    description: str
    strength: MotivationStrength


class CompetitorMention(BaseModel):
    name: str
    context: CompetitorContext
    sentiment_vs_us: CompetitorSentiment
    detail: str


class FeatureRequest(BaseModel):
    feature: str
    urgency: FeatureUrgency
    existing_workaround: Optional[str] = None


class Insights(BaseModel):
    pain_points: list[PainPoint] = []
    motivations: list[Motivation] = []
    competitor_mentions: list[CompetitorMention] = []
    feature_requests: list[FeatureRequest] = []


class ChurnRisk(BaseModel):
    level: ChurnRiskLevel
    factors: list[str] = []
    save_attempted: bool = False
    save_successful: Optional[bool] = None
    save_condition: Optional[str] = Field(
        default=None,
        description="If the save was conditional, describe the condition. "
                    "e.g. 'Customer will cancel if advanced strength content not live by April 15'"
    )


class UpsellOpportunity(BaseModel):
    level: UpsellLevel
    target_plan: Optional[str] = None
    signals: list[str] = []


class Intent(BaseModel):
    primary: str
    secondary: Optional[str] = None
    churn_risk: ChurnRisk
    upsell_opportunity: UpsellOpportunity


class Topic(BaseModel):
    topic: str
    relevance: TopicRelevance
    sentiment: TopicSentiment


class ActionItem(BaseModel):
    action: str
    owner: ActionOwner
    priority: ActionPriority
    status: ActionStatus


class QualityFlags(BaseModel):
    interaction_quality: InteractionQuality
    extraction_confidence: ExtractionConfidence
    requires_human_review: bool
    review_reasons: list[str] = []


# ── Root model ────────────────────────────────────────────────────────────────

class InteractionRecord(BaseModel):
    interaction_id: str
    interaction: InteractionMeta
    customer: Customer
    sentiment: Sentiment
    insights: Insights
    intent: Intent
    topics: list[Topic] = []
    action_items: list[ActionItem] = []
    quality_flags: QualityFlags

    # ── Schema extensions — not in TARGET_SCHEMA.json ────────────────────────
    agent_quality_score: float = Field(default=0.0, description="EXTENSION: computed in Node 5, not in TARGET_SCHEMA")
    conversation_quality_score: float = Field(default=0.0, description="EXTENSION: computed in Node 5, not in TARGET_SCHEMA")
    hover_summary: str = Field(default="", description="EXTENSION: generated by Node 2 summarizer")
    raw_llm_output: str = Field(default="", description="EXTENSION: stored for auditability")


# ── LangGraph Pipeline State ──────────────────────────────────────────────────

class PipelineState(TypedDict):
    file_path: str
    interaction_id: str
    raw_text: str
    channel: str
    summary: str
    raw_llm_output: str
    extracted_dict: dict
    validated_record: Optional[Any]   # InteractionRecord.model_dump() or None
    scores: dict
    retry_count: int
    errors: list
